### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by steom** [decke/smtprelay#92]
Please consider to add http proxy / socks5 proxy support to connect to smtp server

**Comment by decke** [comment]
Could you please describe your use case? I don't get what you want to do.

**Comment by steom** [comment]
Sending request to external smtp when the internet connection is via SOCKS or HTTPS proxies

**Comment by QuantumDisposition** [comment]
I second the Socks5 case. It is needed. Rarely any MTA can properly use a proxy. By simple googling seems like only Exim can. And Exim is a combine, hardly lightweight with easy config.

Without such features like socks5 support, what is your relay really useful for? A 10 lines long config OpenSmtpd can do simple relays.

**Comment by decke** [comment]
Feel free to use any alternative smtpd that works best for you. smtprelay was planned with a very specific usecase and simplicity in mind. For sure it will never be a replacement for a full blown smtpd.

Socks5 support would need to patch smtp.go to setup the socks connection but that is already a forked and extended copy of net/smtp because they refuse new features to that package. So probably it's easier to look around for a suitable smtp library that already supports socks.
