### ISSUE TITLE
retry send

### ISSUE THREAD

**Issue by steom** [decke/smtprelay#95]
please consider to add
a send retry function
when delivery failed with error like dial tcp address for timeout, etc

**Comment by decke** [comment]
smtprelay is directly forwarding the mail and not storing it like full blown smtp servers. So we cannot easily wait for a longer period and then retry because we would be blocking the client in the meantime.
Some clients like dma (Dragonfly Mail Agent) will queue the outgoing mail if it received an error and can retry later.

**Comment by Enrico204** [comment]
@steom you may use a real SMTP server before smtprelay, like Postfix, and configure Postfix to use smtprelay as "smart host" (or "relay host")
